routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::resource('roles', 'RoleController');

Route::resource('systemMenus', 'SystemMenuController');

Route::resource('studentHasCourseInstances', 'StudentHasCourseInstanceController');

Route::resource('courses', 'CourseController');

Route::resource('roleHasSystemMenus', 'RoleHasSystemMenuController');

Route::resource('usersHasEvents', 'UsersHasEventController');

Route::resource('courseInstances', 'CourseInstanceController');

Route::resource('semesters', 'SemesterController');

Route::resource('typeCourses', 'TypeCourseController');

Route::resource('years', 'YearController');

Route::resource('priorities', 'PriorityController');

Route::resource('eventsTypes', 'EventsTypeController');

Route::resource('events', 'EventController');

Route::resource('globalEvents', 'GlobalEventController');

Route::resource('categories', 'CategoryController');

Route::resource('academicYears', 'AcademicYearController');

Route::resource('courseInstanceHasEvents', 'CourseInstanceHasEventController');

Route::resource('users', 'UserController');

Route::resource('usersHasDevices', 'UsersHasDeviceController');

app/Models/RoleHasSystemMenu.php
<?php

namespace App\Models;

//use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;

/**
 * @SWG\Definition(
 *      definition="RoleHasSystemMenu",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="role_id",
 *          description="role_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="system_menu_id",
 *          description="system_menu_id",
 *          type="integer",
 *          format="int32"
 *      )
 * )
 */
class RoleHasSystemMenu extends Model
{
    use SoftDeletes;

    public $table = 'role_has_system_menu';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'role_id',
        'system_menu_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'role_id' => 'integer',
        'system_menu_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function role()
    {
        return $this->belongsTo(\App\Models\Role::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function systemMenu()
    {
        return $this->belongsTo(\App\Models\SystemMenu::class);
    }
}

app/Http/Controllers/RoleHasSystemMenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoleHasSystemMenuRequest;
use App\Http\Requests\UpdateRoleHasSystemMenuRequest;
use App\Repositories\RoleHasSystemMenuRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class RoleHasSystemMenuController extends AppBaseController
{
    /** @var  RoleHasSystemMenuRepository */
    private $roleHasSystemMenuRepository;

    public function __construct(RoleHasSystemMenuRepository $roleHasSystemMenuRepo)
    {
        $this->roleHasSystemMenuRepository = $roleHasSystemMenuRepo;
    }

    /**
     * Display a listing of the RoleHasSystemMenu.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->roleHasSystemMenuRepository->pushCriteria(new RequestCriteria($request));
        $roleHasSystemMenus = $this->roleHasSystemMenuRepository->all();

        return view('role_has_system_menus.index')
            ->with('roleHasSystemMenus', $roleHasSystemMenus);
    }

    /**
     * Show the form for creating a new RoleHasSystemMenu.
     *
     * @return Response
     */
    public function create()
    {
        return view('role_has_system_menus.create');
    }

    /**
     * Store a newly created RoleHasSystemMenu in storage.
     *
     * @param CreateRoleHasSystemMenuRequest $request
     *
     * @return Response
     */
    public function store(CreateRoleHasSystemMenuRequest $request)
    {
        $input = $request->all();

        $roleHasSystemMenu = $this->roleHasSystemMenuRepository->create($input);

        Flash::success('Role Has System Menu saved successfully.');

        return redirect(route('roleHasSystemMenus.index'));
    }

    /**
     * Display the specified RoleHasSystemMenu.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $roleHasSystemMenu = $this->roleHasSystemMenuRepository->findWithoutFail($id);

        if (empty($roleHasSystemMenu)) {
            Flash::error('Role Has System Menu not found');

            return redirect(route('roleHasSystemMenus.index'));
        }

        return view('role_has_system_menus.show')->with('roleHasSystemMenu', $roleHasSystemMenu);
    }

    /**
     * Show the form for editing the specified RoleHasSystemMenu.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $roleHasSystemMenu = $this->roleHasSystemMenuRepository->findWithoutFail($id);

        if (empty($roleHasSystemMenu)) {
            Flash::error('Role Has System Menu not found');

            return redirect(route('roleHasSystemMenus.index'));
        }

        return view('role_has_system_menus.edit')->with('roleHasSystemMenu', $roleHasSystemMenu);
    }

    /**
     * Update the specified RoleHasSystemMenu in storage.
     *
     * @param  int              $id
     * @param UpdateRoleHasSystemMenuRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRoleHasSystemMenuRequest $request)
    {
        $roleHasSystemMenu = $this->roleHasSystemMenuRepository->findWithoutFail($id);

        if (empty($roleHasSystemMenu)) {
            Flash::error('Role Has System Menu not found');

            return redirect(route('roleHasSystemMenus.index'));
        }

        $roleHasSystemMenu = $this->roleHasSystemMenuRepository->update($request->all(), $id);

        Flash::success('Role Has System Menu updated successfully.');

        return redirect(route('roleHasSystemMenus.index'));
    }

    /**
     * Remove the specified RoleHasSystemMenu from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $roleHasSystemMenu = $this->roleHasSystemMenuRepository->findWithoutFail($id);

        if (empty($roleHasSystemMenu)) {
            Flash::error('Role Has System Menu not found');

            return redirect(route('roleHasSystemMenus.index'));
        }

        $this->roleHasSystemMenuRepository->delete($id);

        Flash::success('Role Has System Menu deleted successfully.');

        return redirect(route('roleHasSystemMenus.index'));
    }
}

resources/views/role_has_system_menus/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Role Has System Menu
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'roleHasSystemMenus.store']) !!}

                        @include('role_has_system_menus.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/role_has_system_menus/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Role Has System Menu
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($roleHasSystemMenu, ['route' => ['roleHasSystemMenus.update', $roleHasSystemMenu->id], 'method' => 'patch']) !!}

                        @include('role_has_system_menus.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/role_has_system_menus/fields.blade.php
<!-- Role Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('role_id', 'Role Id:') !!}
    {!! Form::number('role_id', null, ['class' => 'form-control']) !!}
</div>

<!-- System Menu Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('system_menu_id', 'System Menu Id:') !!}
    {!! Form::number('system_menu_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('roleHasSystemMenus.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/role_has_system_menus/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Role Has System Menus</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('roleHasSystemMenus.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('role_has_system_menus.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/role_has_system_menus/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Role Has System Menu
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('role_has_system_menus.show_fields')
                    <a href="{!! route('roleHasSystemMenus.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/role_has_system_menus/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $roleHasSystemMenu->id !!}</p>
</div>

<!-- Role Id Field -->
<div class="form-group">
    {!! Form::label('role_id', 'Role Id:') !!}
    <p>{!! $roleHasSystemMenu->role_id !!}</p>
</div>

<!-- System Menu Id Field -->
<div class="form-group">
    {!! Form::label('system_menu_id', 'System Menu Id:') !!}
    <p>{!! $roleHasSystemMenu->system_menu_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $roleHasSystemMenu->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $roleHasSystemMenu->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $roleHasSystemMenu->deleted_at !!}</p>
</div>

resources/views/role_has_system_menus/table.blade.php
<table class="table table-responsive" id="roleHasSystemMenus-table">
    <thead>
        <tr>
            <th>Role Id</th>
        <th>System Menu Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($roleHasSystemMenus as $roleHasSystemMenu)
        <tr>
            <td>{!! $roleHasSystemMenu->role_id !!}</td>
            <td>{!! $roleHasSystemMenu->system_menu_id !!}</td>
            <td>
                {!! Form::open(['route' => ['roleHasSystemMenus.destroy', $roleHasSystemMenu->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('roleHasSystemMenus.show', [$roleHasSystemMenu->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('roleHasSystemMenus.edit', [$roleHasSystemMenu->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>