routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::resource('roles', 'RoleController');

Route::resource('systemMenus', 'SystemMenuController');

Route::resource('studentHasCourseInstances', 'StudentHasCourseInstanceController');

Route::resource('courses', 'CourseController');

Route::resource('roleHasSystemMenus', 'RoleHasSystemMenuController');

Route::resource('usersHasEvents', 'UsersHasEventController');

Route::resource('courseInstances', 'CourseInstanceController');

Route::resource('semesters', 'SemesterController');

Route::resource('typeCourses', 'TypeCourseController');

Route::resource('years', 'YearController');

Route::resource('priorities', 'PriorityController');

Route::resource('eventsTypes', 'EventsTypeController');

Route::resource('events', 'EventController');

Route::resource('globalEvents', 'GlobalEventController');

Route::resource('categories', 'CategoryController');

Route::resource('academicYears', 'AcademicYearController');

Route::resource('courseInstanceHasEvents', 'CourseInstanceHasEventController');

Route::resource('users', 'UserController');

Route::resource('usersHasDevices', 'UsersHasDeviceController');

app/Models/UsersHasEvent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="UsersHasEvent",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="student_id",
 *          description="student_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="event_id",
 *          description="event_id",
 *          type="integer",
 *          format="int32"
 *      )
 * )
 */
class UsersHasEvent extends Model
{
    use SoftDeletes;

    public $table = 'users_has_events';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    public $hidden = [
        'updated_at',
        'deleted_at'
    ];
    public $fillable = [
        'student_id',
        'event_id',
        'description'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'student_id' => 'integer',
        'event_id' => 'integer',
        'description'=>'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function event()
    {
        return $this->belongsTo(\App\Models\Event::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function user()
    {
        return $this->belongsTo('App\Models\User','student_id');
    }
}

app/Http/Controllers/UsersHasEventController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUsersHasEventRequest;
use App\Http\Requests\UpdateUsersHasEventRequest;
use App\Repositories\UsersHasEventRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class UsersHasEventController extends AppBaseController
{
    /** @var  UsersHasEventRepository */
    private $usersHasEventRepository;

    public function __construct(UsersHasEventRepository $usersHasEventRepo)
    {
        $this->usersHasEventRepository = $usersHasEventRepo;
    }

    /**
     * Display a listing of the UsersHasEvent.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->usersHasEventRepository->pushCriteria(new RequestCriteria($request));
        $usersHasEvents = $this->usersHasEventRepository->all();

        return view('users_has_events.index')
            ->with('usersHasEvents', $usersHasEvents);
    }

    /**
     * Show the form for creating a new UsersHasEvent.
     *
     * @return Response
     */
    public function create()
    {
        return view('users_has_events.create');
    }

    /**
     * Store a newly created UsersHasEvent in storage.
     *
     * @param CreateUsersHasEventRequest $request
     *
     * @return Response
     */
    public function store(CreateUsersHasEventRequest $request)
    {
        $input = $request->all();

        $usersHasEvent = $this->usersHasEventRepository->create($input);

        Flash::success('Users Has Event saved successfully.');

        return redirect(route('usersHasEvents.index'));
    }

    /**
     * Display the specified UsersHasEvent.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $usersHasEvent = $this->usersHasEventRepository->findWithoutFail($id);

        if (empty($usersHasEvent)) {
            Flash::error('Users Has Event not found');

            return redirect(route('usersHasEvents.index'));
        }

        return view('users_has_events.show')->with('usersHasEvent', $usersHasEvent);
    }

    /**
     * Show the form for editing the specified UsersHasEvent.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $usersHasEvent = $this->usersHasEventRepository->findWithoutFail($id);

        if (empty($usersHasEvent)) {
            Flash::error('Users Has Event not found');

            return redirect(route('usersHasEvents.index'));
        }

        return view('users_has_events.edit')->with('usersHasEvent', $usersHasEvent);
    }

    /**
     * Update the specified UsersHasEvent in storage.
     *
     * @param  int              $id
     * @param UpdateUsersHasEventRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUsersHasEventRequest $request)
    {
        $usersHasEvent = $this->usersHasEventRepository->findWithoutFail($id);

        if (empty($usersHasEvent)) {
            Flash::error('Users Has Event not found');

            return redirect(route('usersHasEvents.index'));
        }

        $usersHasEvent = $this->usersHasEventRepository->update($request->all(), $id);

        Flash::success('Users Has Event updated successfully.');

        return redirect(route('usersHasEvents.index'));
    }

    /**
     * Remove the specified UsersHasEvent from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $usersHasEvent = $this->usersHasEventRepository->findWithoutFail($id);

        if (empty($usersHasEvent)) {
            Flash::error('Users Has Event not found');

            return redirect(route('usersHasEvents.index'));
        }

        $this->usersHasEventRepository->delete($id);

        Flash::success('Users Has Event deleted successfully.');

        return redirect(route('usersHasEvents.index'));
    }
}

resources/views/users_has_events/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Users Has Event
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'usersHasEvents.store']) !!}

                        @include('users_has_events.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users_has_events/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Users Has Event
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($usersHasEvent, ['route' => ['usersHasEvents.update', $usersHasEvent->id], 'method' => 'patch']) !!}

                        @include('users_has_events.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/users_has_events/fields.blade.php
<!-- Student Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('student_id', 'Student Id:') !!}
    {!! Form::number('student_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Event Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('event_id', 'Event Id:') !!}
    {!! Form::number('event_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('usersHasEvents.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/users_has_events/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Users Has Events</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('usersHasEvents.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('users_has_events.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/users_has_events/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Users Has Event
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('users_has_events.show_fields')
                    <a href="{!! route('usersHasEvents.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users_has_events/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $usersHasEvent->id !!}</p>
</div>

<!-- Student Id Field -->
<div class="form-group">
    {!! Form::label('student_id', 'Student Id:') !!}
    <p>{!! $usersHasEvent->student_id !!}</p>
</div>

<!-- Event Id Field -->
<div class="form-group">
    {!! Form::label('event_id', 'Event Id:') !!}
    <p>{!! $usersHasEvent->event_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $usersHasEvent->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $usersHasEvent->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $usersHasEvent->deleted_at !!}</p>
</div>

resources/views/users_has_events/table.blade.php
<table class="table table-responsive" id="usersHasEvents-table">
    <thead>
        <tr>
            <th>Student Id</th>
        <th>Event Id</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($usersHasEvents as $usersHasEvent)
        <tr>
            <td>{!! $usersHasEvent->student_id !!}</td>
            <td>{!! $usersHasEvent->event_id !!}</td>
            <td>
                {!! Form::open(['route' => ['usersHasEvents.destroy', $usersHasEvent->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('usersHasEvents.show', [$usersHasEvent->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('usersHasEvents.edit', [$usersHasEvent->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>