routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::resource('roles', 'RoleController');

Route::resource('systemMenus', 'SystemMenuController');

Route::resource('studentHasCourseInstances', 'StudentHasCourseInstanceController');

Route::resource('courses', 'CourseController');

Route::resource('roleHasSystemMenus', 'RoleHasSystemMenuController');

Route::resource('usersHasEvents', 'UsersHasEventController');

Route::resource('courseInstances', 'CourseInstanceController');

Route::resource('semesters', 'SemesterController');

Route::resource('typeCourses', 'TypeCourseController');

Route::resource('years', 'YearController');

Route::resource('priorities', 'PriorityController');

Route::resource('eventsTypes', 'EventsTypeController');

Route::resource('events', 'EventController');

Route::resource('globalEvents', 'GlobalEventController');

Route::resource('categories', 'CategoryController');

Route::resource('academicYears', 'AcademicYearController');

Route::resource('courseInstanceHasEvents', 'CourseInstanceHasEventController');

Route::resource('users', 'UserController');

Route::resource('usersHasDevices', 'UsersHasDeviceController');

app/Models/CourseInstanceHasEvent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="CourseInstanceHasEvent",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="course_instance_id",
 *          description="course_instance_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="event_id",
 *          description="event_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      )
 * )
 */
class CourseInstanceHasEvent extends Model
{
    use SoftDeletes;

    public $table = 'course_instance_has_events';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'course_instance_id',
        'event_id',
        'description'
    ];
    public $hidden = [
        'updated_at',
        'deleted_at'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'course_instance_id' => 'integer',
        'event_id' => 'integer',
        'description' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function courseInstance()
    {
        return $this->belongsTo('App\Models\CourseInstance','course_instance_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function event()
    {
        return $this->belongsTo(\App\Models\Event::class);
    }
}

app/Http/Controllers/CourseInstanceHasEventController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCourseInstanceHasEventRequest;
use App\Http\Requests\UpdateCourseInstanceHasEventRequest;
use App\Repositories\CourseInstanceHasEventRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class CourseInstanceHasEventController extends AppBaseController
{
    /** @var  CourseInstanceHasEventRepository */
    private $courseInstanceHasEventRepository;

    public function __construct(CourseInstanceHasEventRepository $courseInstanceHasEventRepo)
    {
        $this->courseInstanceHasEventRepository = $courseInstanceHasEventRepo;
    }

    /**
     * Display a listing of the CourseInstanceHasEvent.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->courseInstanceHasEventRepository->pushCriteria(new RequestCriteria($request));
        $courseInstanceHasEvents = $this->courseInstanceHasEventRepository->all();

        return view('course_instance_has_events.index')
            ->with('courseInstanceHasEvents', $courseInstanceHasEvents);
    }

    /**
     * Show the form for creating a new CourseInstanceHasEvent.
     *
     * @return Response
     */
    public function create()
    {
        return view('course_instance_has_events.create');
    }

    /**
     * Store a newly created CourseInstanceHasEvent in storage.
     *
     * @param CreateCourseInstanceHasEventRequest $request
     *
     * @return Response
     */
    public function store(CreateCourseInstanceHasEventRequest $request)
    {
        $input = $request->all();

        $courseInstanceHasEvent = $this->courseInstanceHasEventRepository->create($input);

        Flash::success('Course Instance Has Event saved successfully.');

        return redirect(route('courseInstanceHasEvents.index'));
    }

    /**
     * Display the specified CourseInstanceHasEvent.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $courseInstanceHasEvent = $this->courseInstanceHasEventRepository->findWithoutFail($id);

        if (empty($courseInstanceHasEvent)) {
            Flash::error('Course Instance Has Event not found');

            return redirect(route('courseInstanceHasEvents.index'));
        }

        return view('course_instance_has_events.show')->with('courseInstanceHasEvent', $courseInstanceHasEvent);
    }

    /**
     * Show the form for editing the specified CourseInstanceHasEvent.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $courseInstanceHasEvent = $this->courseInstanceHasEventRepository->findWithoutFail($id);

        if (empty($courseInstanceHasEvent)) {
            Flash::error('Course Instance Has Event not found');

            return redirect(route('courseInstanceHasEvents.index'));
        }

        return view('course_instance_has_events.edit')->with('courseInstanceHasEvent', $courseInstanceHasEvent);
    }

    /**
     * Update the specified CourseInstanceHasEvent in storage.
     *
     * @param  int              $id
     * @param UpdateCourseInstanceHasEventRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCourseInstanceHasEventRequest $request)
    {
        $courseInstanceHasEvent = $this->courseInstanceHasEventRepository->findWithoutFail($id);

        if (empty($courseInstanceHasEvent)) {
            Flash::error('Course Instance Has Event not found');

            return redirect(route('courseInstanceHasEvents.index'));
        }

        $courseInstanceHasEvent = $this->courseInstanceHasEventRepository->update($request->all(), $id);

        Flash::success('Course Instance Has Event updated successfully.');

        return redirect(route('courseInstanceHasEvents.index'));
    }

    /**
     * Remove the specified CourseInstanceHasEvent from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $courseInstanceHasEvent = $this->courseInstanceHasEventRepository->findWithoutFail($id);

        if (empty($courseInstanceHasEvent)) {
            Flash::error('Course Instance Has Event not found');

            return redirect(route('courseInstanceHasEvents.index'));
        }

        $this->courseInstanceHasEventRepository->delete($id);

        Flash::success('Course Instance Has Event deleted successfully.');

        return redirect(route('courseInstanceHasEvents.index'));
    }
}

resources/views/course_instance_has_events/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Course Instance Has Event
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'courseInstanceHasEvents.store']) !!}

                        @include('course_instance_has_events.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/course_instance_has_events/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Course Instance Has Event
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($courseInstanceHasEvent, ['route' => ['courseInstanceHasEvents.update', $courseInstanceHasEvent->id], 'method' => 'patch']) !!}

                        @include('course_instance_has_events.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/course_instance_has_events/fields.blade.php
<!-- Course Instance Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('course_instance_id', 'Course Instance Id:') !!}
    {!! Form::number('course_instance_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Event Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('event_id', 'Event Id:') !!}
    {!! Form::number('event_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('courseInstanceHasEvents.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/course_instance_has_events/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Course Instance Has Events</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('courseInstanceHasEvents.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('course_instance_has_events.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/course_instance_has_events/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Course Instance Has Event
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('course_instance_has_events.show_fields')
                    <a href="{!! route('courseInstanceHasEvents.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/course_instance_has_events/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $courseInstanceHasEvent->id !!}</p>
</div>

<!-- Course Instance Id Field -->
<div class="form-group">
    {!! Form::label('course_instance_id', 'Course Instance Id:') !!}
    <p>{!! $courseInstanceHasEvent->course_instance_id !!}</p>
</div>

<!-- Event Id Field -->
<div class="form-group">
    {!! Form::label('event_id', 'Event Id:') !!}
    <p>{!! $courseInstanceHasEvent->event_id !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $courseInstanceHasEvent->description !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $courseInstanceHasEvent->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $courseInstanceHasEvent->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $courseInstanceHasEvent->deleted_at !!}</p>
</div>

resources/views/course_instance_has_events/table.blade.php
<table class="table table-responsive" id="courseInstanceHasEvents-table">
    <thead>
        <tr>
            <th>Course Instance Id</th>
        <th>Event Id</th>
        <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($courseInstanceHasEvents as $courseInstanceHasEvent)
        <tr>
            <td>{!! $courseInstanceHasEvent->course_instance_id !!}</td>
            <td>{!! $courseInstanceHasEvent->event_id !!}</td>
            <td>{!! $courseInstanceHasEvent->description !!}</td>
            <td>
                {!! Form::open(['route' => ['courseInstanceHasEvents.destroy', $courseInstanceHasEvent->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('courseInstanceHasEvents.show', [$courseInstanceHasEvent->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('courseInstanceHasEvents.edit', [$courseInstanceHasEvent->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>