routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');


Route::resource('roles', 'RoleController');

Route::resource('systemMenus', 'SystemMenuController');

Route::resource('studentHasCourseInstances', 'StudentHasCourseInstanceController');

Route::resource('courses', 'CourseController');

Route::resource('roleHasSystemMenus', 'RoleHasSystemMenuController');

Route::resource('usersHasEvents', 'UsersHasEventController');

Route::resource('courseInstances', 'CourseInstanceController');

Route::resource('semesters', 'SemesterController');

Route::resource('typeCourses', 'TypeCourseController');

Route::resource('years', 'YearController');

Route::resource('priorities', 'PriorityController');

Route::resource('eventsTypes', 'EventsTypeController');

Route::resource('events', 'EventController');

Route::resource('globalEvents', 'GlobalEventController');

Route::resource('categories', 'CategoryController');

Route::resource('academicYears', 'AcademicYearController');

Route::resource('courseInstanceHasEvents', 'CourseInstanceHasEventController');

Route::resource('users', 'UserController');

Route::resource('usersHasDevices', 'UsersHasDeviceController');

app/Models/AcademicYear.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="AcademicYear",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="year",
 *          description="year",
 *          type="string"
 *      )
 * )
 */
class AcademicYear extends Model
{
    use SoftDeletes;

    public $table = 'academic_year';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    public $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    public $fillable = [
        'year',
        'start_first_semester',
        'start_second_semester'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'year' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/AcademicYearController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAcademicYearRequest;
use App\Http\Requests\UpdateAcademicYearRequest;
use App\Repositories\AcademicYearRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class AcademicYearController extends AppBaseController
{
    /** @var  AcademicYearRepository */
    private $academicYearRepository;

    public function __construct(AcademicYearRepository $academicYearRepo)
    {
        $this->academicYearRepository = $academicYearRepo;
    }

    /**
     * Display a listing of the AcademicYear.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->academicYearRepository->pushCriteria(new RequestCriteria($request));
        $academicYears = $this->academicYearRepository->all();

        return view('academic_years.index')
            ->with('academicYears', $academicYears);
    }

    /**
     * Show the form for creating a new AcademicYear.
     *
     * @return Response
     */
    public function create()
    {
        return view('academic_years.create');
    }

    /**
     * Store a newly created AcademicYear in storage.
     *
     * @param CreateAcademicYearRequest $request
     *
     * @return Response
     */
    public function store(CreateAcademicYearRequest $request)
    {
        $input = $request->all();

        $academicYear = $this->academicYearRepository->create($input);

        Flash::success('Academic Year saved successfully.');

        return redirect(route('academicYears.index'));
    }

    /**
     * Display the specified AcademicYear.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $academicYear = $this->academicYearRepository->findWithoutFail($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        return view('academic_years.show')->with('academicYear', $academicYear);
    }

    /**
     * Show the form for editing the specified AcademicYear.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $academicYear = $this->academicYearRepository->findWithoutFail($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        return view('academic_years.edit')->with('academicYear', $academicYear);
    }

    /**
     * Update the specified AcademicYear in storage.
     *
     * @param  int              $id
     * @param UpdateAcademicYearRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAcademicYearRequest $request)
    {
        $academicYear = $this->academicYearRepository->findWithoutFail($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        $academicYear = $this->academicYearRepository->update($request->all(), $id);

        Flash::success('Academic Year updated successfully.');

        return redirect(route('academicYears.index'));
    }

    /**
     * Remove the specified AcademicYear from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $academicYear = $this->academicYearRepository->findWithoutFail($id);

        if (empty($academicYear)) {
            Flash::error('Academic Year not found');

            return redirect(route('academicYears.index'));
        }

        $this->academicYearRepository->delete($id);

        Flash::success('Academic Year deleted successfully.');

        return redirect(route('academicYears.index'));
    }
}

resources/views/academic_years/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Academic Year
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'academicYears.store']) !!}

                        @include('academic_years.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/academic_years/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Academic Year
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($academicYear, ['route' => ['academicYears.update', $academicYear->id], 'method' => 'patch']) !!}

                        @include('academic_years.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/academic_years/fields.blade.php
<!-- Year Field -->
<div class="form-group col-sm-6">
    {!! Form::label('year', 'Year:') !!}
    {!! Form::text('year', null, ['class' => 'form-control']) !!}
</div>

<!-- Start First Semester Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start_first_semester', 'Start First Semester:') !!}
    {!! Form::date('start_first_semester', null, ['class' => 'form-control']) !!}
</div>

<!-- Start Second Semester Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start_second_semester', 'Start Second Semester:') !!}
    {!! Form::date('start_second_semester', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('academicYears.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/academic_years/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Academic Years</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('academicYears.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('academic_years.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/academic_years/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Academic Year
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('academic_years.show_fields')
                    <a href="{!! route('academicYears.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/academic_years/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $academicYear->id !!}</p>
</div>

<!-- Year Field -->
<div class="form-group">
    {!! Form::label('year', 'Year:') !!}
    <p>{!! $academicYear->year !!}</p>
</div>

<!-- Start First Semester Field -->
<div class="form-group">
    {!! Form::label('start_first_semester', 'Start First Semester:') !!}
    <p>{!! $academicYear->start_first_semester !!}</p>
</div>

<!-- Start Second Semester Field -->
<div class="form-group">
    {!! Form::label('start_second_semester', 'Start Second Semester:') !!}
    <p>{!! $academicYear->start_second_semester !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $academicYear->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $academicYear->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $academicYear->deleted_at !!}</p>
</div>

resources/views/academic_years/table.blade.php
<table class="table table-responsive" id="academicYears-table">
    <thead>
        <tr>
            <th>Year</th>
        <th>Start First Semester</th>
        <th>Start Second Semester</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($academicYears as $academicYear)
        <tr>
            <td>{!! $academicYear->year !!}</td>
            <td>{!! $academicYear->start_first_semester !!}</td>
            <td>{!! $academicYear->start_second_semester !!}</td>
            <td>
                {!! Form::open(['route' => ['academicYears.destroy', $academicYear->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('academicYears.show', [$academicYear->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('academicYears.edit', [$academicYear->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>